[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.15.1", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
