[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = {version="1.15.1",features = ["v4", "serde"]}
anyhow = "1.0.97"
tracing = "0.1.41"
protocol = { path = "../protocol" }
